name: PlayerXp
version: 0.1-SNAPSHOT
main: tech.dsstudio.minecraft.xp.PlayerXpApi
author: dousha99
depend:
  - ProtocolLib

permissions:
  pxp.read:
    description: Get current PlayerXp value
    default: true
  pxp.write:
    description: Set current PlayerXp value
    default: op

commands:
  pxpr:
    description: Read PlayerXp
    usage: /pxpr <level|bar> [player=self]
    permission: pxp.read
  pxpw:
    description: Master command of PlayerXp
    usage: /pxpw <level|bar> <value> [player=self]
    permission: pxp.write
